apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: kube-system-backup
  namespace: velero
spec:
  schedule: "0 */6 * * *"  # Every 6 hours (cron format)
  template:
    ttl: 240h0m0s
    includedNamespaces:
      - kube-system
